name: Build Wasmtime for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Wasmtime
      uses: actions/checkout@v4
      with:
        repository: bytecodealliance/wasmtime
        submodules: recursive
    - name: Build with cross
      uses: houseabsolute/actions-rust-cross@v1
      with:
        command: build
        target: aarch64-linux-android
        args: "--release -p wasmtime"
        force-use-cross: true
    - name: Create archive of compiled libraries
      run: |
        cd target/aarch64-linux-android/release/
        tar -czvf wasmtime-libs.tar.gz libwasmtime.*
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasmtime-android-libs
        path: target/aarch64-linux-android/release/wasmtime-libs.tar.gz