name: Build Wasmtime for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi:
          - arm64-v8a
          - armeabi-v7a
          - x86
          - x86_64
    steps:
    - name: Checkout Wasmtime
      uses: actions/checkout@v4
      with:
        repository: bytecodealliance/wasmtime
        submodules: recursive
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: "aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, x86_64-linux-android"
    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
    - name: Install cargo-ndk
      run: cargo install cargo-ndk
    - name: Build with cargo-ndk
      run: cargo ndk -t ${{ matrix.abi }} -o artifacts/${{ matrix.abi }} build --release -p wasmtime-c-api
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasmtime-android-libs-${{ matrix.abi }}
        path: artifacts/${{ matrix.abi }}/libwasmtime.so

  combine-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Organize and archive
      run: |
        mkdir -p wasmtime-libs
        mv artifacts/wasmtime-android-libs-arm64-v8a/libwasmtime.so wasmtime-libs/arm64-v8a-libwasmtime.so
        mv artifacts/wasmtime-android-libs-armeabi-v7a/libwasmtime.so wasmtime-libs/armeabi-v7a-libwasmtime.so
        mv artifacts/wasmtime-android-libs-x86/libwasmtime.so wasmtime-libs/x86-libwasmtime.so
        mv artifacts/wasmtime-android-libs-x86_64/libwasmtime.so wasmtime-libs/x86_64-libwasmtime.so
        tar -czvf wasmtime-libs.tar.gz -C wasmtime-libs .
    - name: Upload combined artifact
      uses: actions/upload-artifact@v4
      with:
        name: wasmtime-android-libs
        path: wasmtime-libs.tar.gz