name: Build Wasmtime for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build with cross
      uses: cross-rs/cross@v0
      with:
        target: aarch64-linux-android
        args: --release -p wasmtime